---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: webserver
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 2
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver
          image: nginx:1.22
          ports:
            - containerPort: 80
